config/routes.rb
Rails.application.routes.draw do
  resources :admin_posts
  devise_for :users,
             controllers: {
               registrations: 'users/registrations',
               sessions: 'users/sessions',
             }
  devise_scope :user do
    root 'users#index'
  end
  resources :users, only: %i[index show] do
    member do
      delete :destroy_by_admin
      patch :change_suitable
    end
    collection { get :administrator }
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  has_one_attached :image

  validates :image,
            content_type: %i[gif png jpg jpeg],
            size: {
              less_than_or_equal_to: 5.megabytes,
            },
            dimension: {
              width: {
                max: 3000,
              },
              height: {
                max: 3000,
              },
            }
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end
  # POST /resource/confirmation
  # def create
  #   super
  # end
  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end
  # protected
  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  # GET /resource/sign_up
  # def new
  #   super
  # end
  # POST /resource
  # def create
  #   super
  # end
  # GET /resource/edit
  # def edit
  #   super
  # end
  # PUT /resource
  # def update
  #   super
  # end
  # DELETE /resource
  def destroy
    resource.destroy
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    set_flash_message! :notice, :destroyed
    yield resource if block_given?

    # status:とnotice:を追加
    respond_with_navigational(resource) do
      redirect_to after_sign_out_path_for(resource_name),
                  status: :see_other,
                  notice: find_message(:destroyed)
    end
  end
  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end
  # protected
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end
  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end
  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  # GET /resource/sign_in
  # def new
  #   super
  # end
  # POST /resource/sign_in
  # def create
  #   super
  # end
  # DELETE /resource/sign_out
  def destroy
    signed_out =
      (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
    set_flash_message! :notice, :signed_out if signed_out
    yield if block_given?
    respond_to do |format|
      format.all { head :no_content }
      format.any(*navigational_formats) do
        redirect_to after_sign_out_path_for(resource_name),
                    status: :see_other,
                    notice: find_message(:signed_out)
      end
    end
  end
  # protected
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_admin,
                only: %i[administrator destroy_by_admin change_suitable]

  # before Action
  def check_admin
    if user_signed_in?
      redirect_to users_path if current_user.admin == false
    else
      redirect_to users_path
    end
  end

  # action
  def index
    basic_users = User.where.not(admin: true).where.not(suitable: false)
    @users =
      if params[:q]
        basic_users.where('name LIKE ?', "%#{params[:q]}%").page(params[:page])
      else
        basic_users.page(params[:page])
      end
  end

  def show
    @user = User.find(params[:id])
  end

  def administrator
    @unsuitable_user = User.where(suitable: false)
    @suitable_user = User.where.not(admin: true).where.not(suitable: false)
  end

  # administratorで実行する削除メソッド
  def destroy_by_admin
    @user = User.find(params[:id])
    @user.destroy
    redirect_to administrator_users_path
  end

  def change_suitable
    @user = User.find(params[:id])
    if @user.suitable == true
      @user.update_attribute(:suitable, false)
    else
      @user.update_attribute(:suitable, true)
    end
    redirect_to administrator_users_path
  end

  private

  def user_params
    params.require(:user).permit(:suitable)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/administrator.html.erb
<p class=" text-2xl my-20">管理画面</p>
<div class="grid grid-cols-2">

    <div class="mx-10">
        <p class="border-dashed border-gray-700 p-5 border-2">ユーザー一覧</p>
        <div class="grid grid-cols-2 gap-3">
            <% @suitable_user.each do |user| %>
            <div class=" py-5 px-2 shadow-md">
                <p>メールアドレス：<%= user.email %></p>
                <p><%= user.description %></p>
                <%= link_to "編集", edit_user_registration_path(user)%>
                <%= button_to "削除", destroy_by_admin_user_path(user), method: :delete %>
                <%= button_to "表示変更", change_suitable_user_path(user), method: :patch %>
            </div>
            <% end%>
        </div>
    </div>

    <div class="mx-10">
        <p class="border-dashed border-gray-700 p-5 border-2">不適切なユーザー</p>
        <div class="grid grid-cols-2 gap-3">
            <% @unsuitable_user.each do |user| %>
            <div class="py-5 px-2 shadow-md">
                <p>メールアドレス：<%= user.email %></p>
                <p><%= user.description %></p>
                <%= link_to "編集", edit_user_registration_path(user)%>
                <%= button_to "削除", destroy_by_admin_user_path(user), method: :delete %>
                <%= button_to "表示変更", change_suitable_user_path(user), method: :patch %>
            </div>
            <% end%>
        </div>
    </div>

</div>

app/views/users/index.html.erb
<div class="text-center">

  <h1 class="my-10">サークル一覧</h1>
  <%= form_tag users_path, method: :get, data: {turbo_frame: :users} do %>
  <%= text_field_tag :q, params[:q],autofocus: true, oninput: "requestSubmit()" %>
  <% end %>

  <%= turbo_frame_tag :users do %>
  <div class="grid grid-cols-3 m-10 gap-5">
    <% @users.each do |user| %>
    <div class=" py-5 px-2 shadow-md">
      <% if user.image.attached? %>
      <%= image_tag(user.image)%>
      <% else %>
      <div class="image bg-slate-800 w-full h-40"></div>
      <% end %>

      <p class="text-center text-2xl my-10"><%= link_to user.name , user_path(user) %></p>
      <p class=" my-10"><%= user.description %></p>
      <div class="grid grid-cols-1">
        <% if user_signed_in? %>
        <% if current_user == user %>
        <%= link_to "編集", edit_user_registration_path(user)%>
        <%= button_to "アカウントの削除", registration_path(user), method: :delete %>
        <% end %>
        <% end %>
        <%= link_to "詳細", user_path(user)%>
      </div>
    </div>
    <% end %>
  </div>
  <% end %>
  <%= paginate @users %>


</div>

app/views/users/show.html.erb
<h1 class=" text-2xl my-10">詳細ページ</h1>
<div class="m-40">
    <div class="grid grid-cols-2 shadow-2xl">
        <div class=" justify-center items-center flex">
            <% if @user.image.attached? %>
            <%= image_tag(@user.image)%>
            <% else %>
            <div class="image bg-slate-800 w-full h-40"></div>
            <% end %>
        </div>

        <div class="py-10 px-2">
            <% if @user.admin === true %>
            <p>userはいません</p>
            <% else %>
            <p class="user-name">名前：<%= @user.name %></p>
            <p>メールアドレス：<%= @user.email %></p>

            <p>説明：<%= @user.description %></p>
            <% end %>
        </div>
    </div>

</div>