config/routes.rb
Rails.application.routes.draw do
  resources :admin_posts
  devise_for :users,
             controllers: {
               registrations: 'users/registrations',
               sessions: 'users/sessions',
             }
  devise_scope :user do
    root 'users#index'
  end
  resources :users, only: %i[index show] do
    member do
      delete :destroy_by_admin
      patch :change_suitable
    end
    collection { get :administrator }
  end
end

app/controllers/admin_posts_controller.rb
class AdminPostsController < ApplicationController
  include Admin
  before_action :check_admin
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.create(post_params)
    if @post.save
      flash[:success] = '投稿完了'
      redirect_to admin_posts_path
    else
      flash.now[:alert] = 'メッセージを入力してください。'
      render 'new'
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:success] = 'admin postアップデート'
      redirect_to admin_posts_path
    else
      render 'edit'
    end
  end

  def destroy; end

  private

  def post_params
    params
      .require(:post)
      .permit(:title, :content)
      .merge(user_id: current_user.id)
  end
end

app/helpers/admin_post_helper.rb
module AdminPostHelper
end

app/views/admin_posts/edit.html.erb
<div>
  <h1 class=" font-extrabold text-3xl my-4">[<%=@post.title%>]編集</h1>
</div>
<%= form_with model:@post, url:admin_post_path, local: true do |f| %>
<div class=" grid grid-cols-1 text-center mx-40">
  <%= f.text_field :title, placeholder: "title", class: "search-input mt-10"%>
  <%= f.text_area :content, placeholder: "content", class: "search-input my-10"%>
  <%= f.submit "admin-post" %>
</div>
<% end %>

app/views/admin_posts/index.html.erb
<div>
  <h1 class=" font-extrabold text-3xl my-4">お知らせ</h1>
  <% @posts.each do |post| %>
  <div class="py-5 px-2 mx-40 shadow-md">
    <h2 class=" font-extrabold text-3xl my-4">title:<%=post.title%></h2>
    <p><%=post.content%></p>
    <%= link_to "edit", edit_admin_post_path(post.id), class:"px-3" %>
  </div>
  <% end %>
</div>

app/views/admin_posts/new.html.erb
<div>
  <h1 class="font-bold text-4xl">AdminPost#new</h1>
  <p>Find me in app/views/admin_post/new.html.erb</p>
</div>
<%= form_with model:@post,url:admin_posts_path, local: true do |f| %>
<div class=" grid grid-cols-1 text-center mx-40">
  <%= f.text_field :title, placeholder: "title", class: "search-input mt-10"%>
  <%= f.text_area :content, placeholder: "content", class: "search-input my-10"%>
  <%= f.submit "admin-post", class: "search-btn" %>
</div>
<% end %>