config/routes.rb
Rails.application.routes.draw do
  resources :admin_posts
  devise_for :users,
             controllers: {
               registrations: 'users/registrations',
               sessions: 'users/sessions',
             }
  devise_scope :user do
    root 'users#index'
  end
  resources :users, only: %i[index show] do
    member do
      delete :destroy_by_admin
      patch :change_suitable
    end
    collection { get :administrator }
  end
end

app/views/layouts/_flash.html.erb
<div class="text-center">
    <% if notice %>
    <div class=" bg-lime-400 mx-24 my-10 py-5 shadow-2xl rounded-md">
        <p class="alert alert-notice"><%= notice %></p>
    </div>

    <% end %>
    <% if alert %>
    <div class=" bg-orange-400 mx-24 my-10 py-5 shadow-2xl rounded-md">
        <p class="alert alert-error"><%= alert %></p>
    </div>
    <% end %>
</div>

<div class="text-center">
    <% if flash[:success] %>
    <div class=" bg-lime-400 mx-24 my-10 py-5 shadow-2xl rounded-md">
        <p class="alert alert-notice"><%= flash[:success] %></p>
    </div>

    <% end %>
    <% if flash[:alert] %>
    <div class=" bg-orange-400 mx-24 my-10 py-5 shadow-2xl rounded-md">
        <p class="alert alert-error"><%= flash[:alert] %></p>
    </div>
    <% end %>
</div>

app/views/layouts/_header.html.erb
  <div class="text-center grid grid-cols-8 basic-color text-white">
    <div class="grid grid-cols-3 col-span-2">
      <div class="text-center justify-center">
        <%= image_tag 'Logo.svg', class:"w-10 m-auto my-10"%>
      </div>
      <h1 class="flex items-center justify-left ont-extrabold text-3xl">Dempathy</h1>
    </div>
    <div class="col-span-3 col-start-6 flex items-center justify-center">
      <%= link_to "ユーザ一覧", users_path, class:"px-3" %>
      <% if user_signed_in? %>
      <%= link_to "登録編集", edit_user_registration_path, class:"px-3" %>
      <%= button_to "ログアウト", destroy_user_session_path, class:"px-3", method: :delete %>
      <% if current_user.admin == true %>
      <%= link_to "adminuser", administrator_users_path, class:"px-3" %>
      <%= link_to "admin post投稿", new_admin_post_path, class:"px-3" %>
      <%= link_to "admin post一覧", admin_posts_path, class:"px-3" %>

      <% end %>
      <% else %>
      <%= link_to "新規登録", new_user_registration_path, class:"px-3" %>
      <%= link_to "ログイン", user_session_path, class:"px-3" %>
      <% end %>


    </div>

  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Dempathy</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
  <%= render partial: 'layouts/header'%>
  <%= render partial: "layouts/flash" ,status: :unprocessable_entity %>
  <div class="text-center">
    <%= yield %>
  </div>

</body>

</html>